#!/usr/bin/env bash

# We'll be handed the list of files added/modified in a PR.
# From that, extract the list of exercise directories, and
# test there.

minorVer=$(IFS="."; echo "${BASH_VERSINFO[*]:0:2}")

if [[ $minorVer < "4.3" ]]; then
    echo "[Failure] This script requires bash version 4.3+" >&2
    exit 1
fi

declare -A seen=()
status=0

for file; do
    dir=$(dirname "$file")
    if [[ ! -v seen["$dir"] ]]; then
        seen["$dir"]=1
        bin/validate_one_exercise "$dir" || status=1
    fi
done

exit $status
