#!/usr/bin/env bash

# We'll be handed the list of files added/modified in a PR.
# From that, extract the list of exercise directories, and
# test there.

if ((BASH_VERSINFO[0] < 4)); then
    echo "[Failure] This script requires bash version 4+" >&2
    exit 4
fi

declare -A seen=()
status=0

for file; do
    dir=$(dirname "$file")

    # this file is NOT under the exercises dir: nothing to test
    [[ $dir == exercises/* ]] || continue

    dir=${dir%/.meta}       # for instance the example file

    if [[ -z ${seen[$dir]} ]]; then
        seen["$dir"]=yes
        bin/validate_one_exercise "$dir" || status=1
    fi
done

exit $status
