#!/usr/bin/env bash

# This stub should help you get started:
# - Bash is flexible. You may use functions or write a raw script.
#
# - Complex code can be made easier to read by breaking it up
#   into functions, however this is sometimes overkill in bash.
#
# - For more info about good style in bash visit:
#   https://google.github.io/styleguide/shell.xml
#
#   Example:
#   # other functions here
#   # ...
#   # ...
#
#   main () {
#   # your main function code here
#   }
#
#   # call main with all of the positional arguments
#   main "$@"
#
# *** REMOVE THIS STUB BEFORE SUBMITTING YOUR SOLUTION FOR MENTORING ***
