#!/usr/bin/env bash

# This is a stub for exercises on the exercism.io bash track.
#
# The following information should help you get started:
# - Bash is flexible. You may use functions or write a raw script
#
# - Keep in mind that more complex solutions will benefit greatly
#   concerning readability when code is compartmentalized into
#   functions. However, sometimes in bash functions are just overkill.
#
# - If you use functions then you should have a function named main
#   as the entry point into your script.
#
#   NB. main may be defined at the end (as below) or at the beginning.
#       It should not be defined mixed in with other functions!
#
#   It's implementation would be like the following:
#
#   # other functions here
#   .
#   .
#   .
#
#   main () {
#   # your main function code here
#   }
#
#   # dont forget to call it at the end
#   # this calls main with all of the positional arguments
#   main "$@"
#
# *** REMOVE THIS STUB BEFORE SUBMITTING YOUR SOLUTION FOR MENTORING ***
